USE sodec;

INSERT INTO devices (name, description) VALUES
('s-temp-out', "the temperature in the outside north wall"),
('s-temp-bed', "the temperature in the bedroom"),
('s-temp-bath', "the temperature in the bathroom"),
('s-temp-lr', "the temperature in the living room"),
('s-hum-out', "the humidity in the outside north wall"),
('s-hum-bed', "the humidity in the outside bedroom"),
('s-hum-bath', "the humidity in the outside bathroom"),
('s-hum-lr', "the humidity in the outside living room"),
('s-occ-bed', "whether the bedroom is occupied"),
('s-occ-mech', "whether the mechanical room is occupied"),
('s-occ-lr', "whether the living room is occupied"),
('s-occ-bath', "whether the bathroom is occupied"),
('s-amb-bed', "the ambient light level in the bedroom"),
('s-amb-mech', "the ambient light level in the mechanical room"),
('s-amb-lr', "the ambient light level in the living room"),
('s-amb-bath', "the ambient light level in the bathroom"),
('c-light-bed', "control of the lights in the bedroom"),
('c-light-lr', "control of the lights in the living room"),
('c-light-kit', "control of the lights in the kitchen"),
('s-elec-used-laundry', "energy consumption for dryer/washer circuit"),
('s-elec-used-dishwasher', "energy consumption for dishwasher circuit"),
('s-elec-used-refrigerator', "energy consumption for refrigerator circuit"),
('s-elec-used-induction-stove', "energy consumption for induction stove circuit"),
('s-elec-used-ewh-solar-water-heater', "energy consumption for ewh solar water heater circuit"),
('s-elec-used-kitchen-receps-1', "energy consumption for kitchen receps 1 circuit"),
('s-elec-used-kitchen-receps-2', "energy consumption for kitchen receps 2 circuit"),
('s-elec-used-living-receps', "energy consumption for living room receps circuit"),
('s-elec-used-dining-receps-1', "energy consumption for dining room receps 1 circuit"),
('s-elec-used-dining-receps-2', "energy consumption for dining room receps 2 circuit"),
('s-elec-used-bathroom-receps', "energy consumption for bathroom receps circuit"),
('s-elec-used-bedroom-receps-1', "energy consumption for bedroom receps 1 circuit"),
('s-elec-used-bedroom-receps-2', "energy consumption for bedroom receps 2 circuit"),
('s-elec-used-mechanical-receps', "energy consumption for mechanical room receps circuit"),
('s-elec-used-entry-receps', "energy consumption for entry room receps circuit"),
('s-elec-used-exterior-receps', "energy consumption for exterior receps circuit"),
('s-elec-used-grey-water-pump-receps', "energy consumption for grey water pump receps circuit"),
('s-elec-used-black-water-pump-receps', "energy consumption for black water pump receps circuit"),
('s-elec-used-thermal-loop-pump-receps', "energy consumption for thermal loop pump receps circuit"),
('s-elec-used-water-supply-pump-receps', "energy consumption for water supply pump receps circuit"),
('s-elec-used-water-supply-booster-pump-receps', "energy consumption for water supply booster pump receps circuit"),
('s-elec-used-vehicle-charging-recep', 'energy consumption for vehicle charging recep circuit'),
('s-elec-used-heat-pump-recep', 'energy consumption for vehicle charging recep circuit'),
('s-elec-used-air-handler-recep', 'energy consumption for air handler charging recep circuit'),
('s-temp-testing-blackhole', 'a temperature bin to test recording'),
('s-temp-testing-empty', 'a temperature bin that\'s always empty'),
('s-light-entry-bookend-1A', ''),
('s-light-chandelier-1B', ''),
('s-light-tv-light-2A', '')
('s-light-kitchen-uplight-2A', ''),
('s-light-under-counter-3B', ''),
('s-light-pendant-bar-lights-3C', ''),
('s-light-bathroom-ambient-4A', ''),
('s-light-mirror-4B', ''),
('s-light-flexspace-uplight-6A', ''),
('s-light-flexspace-uplight-6B', ''),
('s-light-bedroom-uplight-6A', ''),
('s-light-bedroom-uplight-6B', ''),
('s-light-porch-lights-8A', ''),
('s-light-uplights-and-pot-lights-8B', '');
