#lang racket/base

(provide example-forecast
         example-forecast-ms)

(define example-forecast-ms (* 1442087730 1000))

(define example-forecast
    '#hasheq((latitude . 33.673676)
             (longitude . -117.741895)
             (currently
              .
              #hasheq((nearestStormDistance . 8)
                      (nearestStormBearing . 206)
                      (precipIntensity . 0)
                      (visibility . 16.09)
                      (precipProbability . 0)
                      (temperature . 30.39)
                      (apparentTemperature . 31.46)
                      (dewPoint . 18.45)
                      (humidity . 0.49)
                      (windSpeed . 2.88)
                      (time . 1442087730)
                      (windBearing . 231)
                      (cloudCover . 0.77)
                      (pressure . 1013.79)
                      (ozone . 281.62)
                      (icon . "partly-cloudy-day")
                      (summary . "Mostly Cloudy")))
             (minutely
              .
              #hasheq((data
                       .
                       (#hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442087700))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442087760))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442087820))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442087880))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442087940))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442088000))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442088060))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442088120))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442088180))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442088240))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442088300))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442088360))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442088420))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442088480))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442088540))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442088600))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442088660))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442088720))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442088780))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442088840))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442088900))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442088960))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442089020))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442089080))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442089140))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442089200))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442089260))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442089320))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442089380))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442089440))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442089500))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442089560))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442089620))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442089680))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442089740))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442089800))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442089860))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442089920))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442089980))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442090040))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442090100))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442090160))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442090220))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442090280))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442090340))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442090400))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442090460))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442090520))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442090580))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442090640))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442090700))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442090760))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442090820))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442090880))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442090940))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442091000))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442091060))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442091120))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442091180))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442091240))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (time . 1442091300))))
                      (icon . "partly-cloudy-day")
                      (summary . "Mostly cloudy for the hour.")))
             (hourly
              .
              #hasheq((data
                       .
                       (#hasheq((precipIntensity . 0)
                                (visibility . 16.09)
                                (precipProbability . 0)
                                (temperature . 29.77)
                                (apparentTemperature . 30.97)
                                (dewPoint . 18.76)
                                (humidity . 0.52)
                                (windSpeed . 2.03)
                                (time . 1442084400)
                                (windBearing . 224)
                                (cloudCover . 0.65)
                                (pressure . 1014.01)
                                (ozone . 281.8)
                                (icon . "partly-cloudy-day")
                                (summary . "Mostly Cloudy"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 16.09)
                                (precipProbability . 0)
                                (temperature . 30.44)
                                (apparentTemperature . 31.5)
                                (dewPoint . 18.42)
                                (humidity . 0.49)
                                (windSpeed . 2.95)
                                (time . 1442088000)
                                (windBearing . 232)
                                (cloudCover . 0.78)
                                (pressure . 1013.78)
                                (ozone . 281.6)
                                (icon . "partly-cloudy-day")
                                (summary . "Mostly Cloudy"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 16.09)
                                (precipProbability . 0)
                                (temperature . 31.27)
                                (apparentTemperature . 32.64)
                                (dewPoint . 18.89)
                                (humidity . 0.48)
                                (windSpeed . 3.42)
                                (time . 1442091600)
                                (windBearing . 245)
                                (cloudCover . 0.8)
                                (pressure . 1013.38)
                                (ozone . 281.34)
                                (icon . "partly-cloudy-day")
                                (summary . "Mostly Cloudy"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 16.09)
                                (precipProbability . 0)
                                (temperature . 31.7)
                                (apparentTemperature . 33.46)
                                (dewPoint . 19.44)
                                (humidity . 0.48)
                                (windSpeed . 3.7)
                                (time . 1442095200)
                                (windBearing . 256)
                                (cloudCover . 0.82)
                                (pressure . 1012.84)
                                (ozone . 280.89)
                                (icon . "partly-cloudy-day")
                                (summary . "Mostly Cloudy"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 16.09)
                                (precipProbability . 0)
                                (temperature . 31.8)
                                (apparentTemperature . 33.98)
                                (dewPoint . 20.03)
                                (humidity . 0.5)
                                (windSpeed . 3.88)
                                (time . 1442098800)
                                (windBearing . 263)
                                (cloudCover . 0.8)
                                (pressure . 1012.23)
                                (ozone . 280.39)
                                (icon . "partly-cloudy-day")
                                (summary . "Mostly Cloudy"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 16.09)
                                (precipProbability . 0)
                                (temperature . 31.48)
                                (apparentTemperature . 33.89)
                                (dewPoint . 20.43)
                                (humidity . 0.52)
                                (windSpeed . 3.81)
                                (time . 1442102400)
                                (windBearing . 265)
                                (cloudCover . 0.78)
                                (pressure . 1011.82)
                                (ozone . 280.26)
                                (icon . "partly-cloudy-day")
                                (summary . "Mostly Cloudy"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 16.09)
                                (precipProbability . 0)
                                (temperature . 30.03)
                                (apparentTemperature . 32.11)
                                (dewPoint . 20.27)
                                (humidity . 0.56)
                                (windSpeed . 3.73)
                                (time . 1442106000)
                                (windBearing . 271)
                                (cloudCover . 0.78)
                                (pressure . 1011.66)
                                (ozone . 280.81)
                                (icon . "partly-cloudy-day")
                                (summary . "Mostly Cloudy"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 15.95)
                                (precipProbability . 0)
                                (temperature . 28.15)
                                (apparentTemperature . 29.84)
                                (dewPoint . 20.01)
                                (humidity . 0.61)
                                (windSpeed . 3.11)
                                (time . 1442109600)
                                (windBearing . 273)
                                (cloudCover . 0.74)
                                (pressure . 1011.77)
                                (ozone . 281.73)
                                (icon . "partly-cloudy-night")
                                (summary . "Mostly Cloudy"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 15.8)
                                (precipProbability . 0)
                                (temperature . 26.73)
                                (apparentTemperature . 28.16)
                                (dewPoint . 19.91)
                                (humidity . 0.66)
                                (windSpeed . 2.36)
                                (time . 1442113200)
                                (windBearing . 272)
                                (cloudCover . 0.74)
                                (pressure . 1011.95)
                                (ozone . 282.49)
                                (icon . "partly-cloudy-night")
                                (summary . "Mostly Cloudy"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 15.71)
                                (precipProbability . 0)
                                (temperature . 26.04)
                                (apparentTemperature . 26.04)
                                (dewPoint . 19.95)
                                (humidity . 0.69)
                                (windSpeed . 1.6)
                                (time . 1442116800)
                                (windBearing . 258)
                                (cloudCover . 0.59)
                                (pressure . 1012.22)
                                (ozone . 282.96)
                                (icon . "partly-cloudy-night")
                                (summary . "Partly Cloudy"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 15.63)
                                (precipProbability . 0)
                                (temperature . 25.14)
                                (apparentTemperature . 25.14)
                                (dewPoint . 19.63)
                                (humidity . 0.72)
                                (windSpeed . 1.39)
                                (time . 1442120400)
                                (windBearing . 239)
                                (cloudCover . 0.56)
                                (pressure . 1012.55)
                                (ozone . 283.27)
                                (icon . "partly-cloudy-night")
                                (summary . "Partly Cloudy"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 15.42)
                                (precipProbability . 0)
                                (temperature . 24.33)
                                (apparentTemperature . 24.33)
                                (dewPoint . 19.37)
                                (humidity . 0.74)
                                (windSpeed . 1.38)
                                (time . 1442124000)
                                (windBearing . 226)
                                (cloudCover . 0.51)
                                (pressure . 1012.73)
                                (ozone . 283.32)
                                (icon . "partly-cloudy-night")
                                (summary . "Partly Cloudy"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 15.16)
                                (precipProbability . 0)
                                (temperature . 23.57)
                                (apparentTemperature . 23.57)
                                (dewPoint . 19.32)
                                (humidity . 0.77)
                                (windSpeed . 1.25)
                                (time . 1442127600)
                                (windBearing . 211)
                                (cloudCover . 0.56)
                                (pressure . 1012.67)
                                (ozone . 283.02)
                                (icon . "partly-cloudy-night")
                                (summary . "Partly Cloudy"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 15.03)
                                (precipProbability . 0)
                                (temperature . 23.02)
                                (apparentTemperature . 23.02)
                                (dewPoint . 19.19)
                                (humidity . 0.79)
                                (windSpeed . 1.09)
                                (time . 1442131200)
                                (windBearing . 200)
                                (cloudCover . 0.42)
                                (pressure . 1012.47)
                                (ozone . 282.45)
                                (icon . "partly-cloudy-night")
                                (summary . "Partly Cloudy"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 14.87)
                                (precipProbability . 0)
                                (temperature . 22.47)
                                (apparentTemperature . 22.47)
                                (dewPoint . 18.89)
                                (humidity . 0.8)
                                (windSpeed . 0.94)
                                (time . 1442134800)
                                (windBearing . 200)
                                (cloudCover . 0.34)
                                (pressure . 1012.25)
                                (ozone . 281.8)
                                (icon . "partly-cloudy-night")
                                (summary . "Partly Cloudy"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 14.74)
                                (precipProbability . 0)
                                (temperature . 22.17)
                                (apparentTemperature . 22.17)
                                (dewPoint . 18.86)
                                (humidity . 0.82)
                                (windSpeed . 0.83)
                                (time . 1442138400)
                                (windBearing . 203)
                                (cloudCover . 0.31)
                                (pressure . 1012.02)
                                (ozone . 281.02)
                                (icon . "partly-cloudy-night")
                                (summary . "Partly Cloudy"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 14.55)
                                (precipProbability . 0)
                                (temperature . 22)
                                (apparentTemperature . 22)
                                (dewPoint . 18.93)
                                (humidity . 0.83)
                                (windSpeed . 0.65)
                                (time . 1442142000)
                                (windBearing . 228)
                                (cloudCover . 0.23)
                                (pressure . 1011.78)
                                (ozone . 280.15)
                                (icon . "clear-night")
                                (summary . "Clear"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 14.24)
                                (precipProbability . 0)
                                (temperature . 22.16)
                                (apparentTemperature . 22.16)
                                (dewPoint . 19.31)
                                (humidity . 0.84)
                                (windSpeed . 0.68)
                                (time . 1442145600)
                                (windBearing . 252)
                                (cloudCover . 0.36)
                                (pressure . 1011.64)
                                (ozone . 279.46)
                                (icon . "partly-cloudy-night")
                                (summary . "Partly Cloudy"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 15)
                                (precipProbability . 0)
                                (temperature . 22.64)
                                (apparentTemperature . 22.64)
                                (dewPoint . 19.72)
                                (humidity . 0.84)
                                (windSpeed . 0.58)
                                (time . 1442149200)
                                (windBearing . 243)
                                (cloudCover . 0.36)
                                (pressure . 1011.7)
                                (ozone . 279.05)
                                (icon . "partly-cloudy-night")
                                (summary . "Partly Cloudy"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 15.5)
                                (precipProbability . 0)
                                (temperature . 23.48)
                                (apparentTemperature . 23.48)
                                (dewPoint . 20.19)
                                (humidity . 0.82)
                                (windSpeed . 0.46)
                                (time . 1442152800)
                                (windBearing . 237)
                                (cloudCover . 0.44)
                                (pressure . 1011.86)
                                (ozone . 278.8)
                                (icon . "partly-cloudy-day")
                                (summary . "Partly Cloudy"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 9.51)
                                (precipProbability . 0)
                                (temperature . 24.83)
                                (apparentTemperature . 24.83)
                                (dewPoint . 20.41)
                                (humidity . 0.77)
                                (windSpeed . 0.59)
                                (time . 1442156400)
                                (windBearing . 240)
                                (cloudCover . 0.46)
                                (pressure . 1011.96)
                                (ozone . 278.65)
                                (icon . "partly-cloudy-day")
                                (summary . "Partly Cloudy"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 9.53)
                                (precipProbability . 0)
                                (temperature . 26.47)
                                (apparentTemperature . 26.47)
                                (dewPoint . 20.91)
                                (humidity . 0.72)
                                (windSpeed . 1.15)
                                (time . 1442160000)
                                (windBearing . 244)
                                (cloudCover . 0.46)
                                (pressure . 1011.95)
                                (ozone . 278.54)
                                (icon . "partly-cloudy-day")
                                (summary . "Partly Cloudy"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 9.93)
                                (precipProbability . 0)
                                (temperature . 28.3)
                                (apparentTemperature . 30.42)
                                (dewPoint . 20.82)
                                (humidity . 0.64)
                                (windSpeed . 2.16)
                                (time . 1442163600)
                                (windBearing . 245)
                                (cloudCover . 0.45)
                                (pressure . 1011.85)
                                (ozone . 278.52)
                                (icon . "partly-cloudy-day")
                                (summary . "Partly Cloudy"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 11.99)
                                (precipProbability . 0)
                                (temperature . 30.19)
                                (apparentTemperature . 32.8)
                                (dewPoint . 21.01)
                                (humidity . 0.58)
                                (windSpeed . 3.05)
                                (time . 1442167200)
                                (windBearing . 247)
                                (cloudCover . 0.44)
                                (pressure . 1011.62)
                                (ozone . 278.63)
                                (icon . "partly-cloudy-day")
                                (summary . "Partly Cloudy"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 16.09)
                                (precipProbability . 0)
                                (temperature . 31.48)
                                (apparentTemperature . 34.51)
                                (dewPoint . 21.22)
                                (humidity . 0.55)
                                (windSpeed . 3.77)
                                (time . 1442170800)
                                (windBearing . 249)
                                (cloudCover . 0.36)
                                (pressure . 1011.17)
                                (ozone . 278.89)
                                (icon . "partly-cloudy-day")
                                (summary . "Partly Cloudy"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 16.09)
                                (precipProbability . 0)
                                (temperature . 31.78)
                                (apparentTemperature . 35.01)
                                (dewPoint . 21.39)
                                (humidity . 0.54)
                                (windSpeed . 4.41)
                                (time . 1442174400)
                                (windBearing . 250)
                                (cloudCover . 0.25)
                                (pressure . 1010.6)
                                (ozone . 279.28)
                                (icon . "partly-cloudy-day")
                                (summary . "Partly Cloudy"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 16.09)
                                (precipProbability . 0)
                                (temperature . 31.92)
                                (apparentTemperature . 35.32)
                                (dewPoint . 21.55)
                                (humidity . 0.54)
                                (windSpeed . 4.94)
                                (time . 1442178000)
                                (windBearing . 252)
                                (cloudCover . 0.17)
                                (pressure . 1010.04)
                                (ozone . 279.8)
                                (icon . "clear-day")
                                (summary . "Clear"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 16.09)
                                (precipProbability . 0)
                                (temperature . 31.02)
                                (apparentTemperature . 33.77)
                                (dewPoint . 20.98)
                                (humidity . 0.55)
                                (windSpeed . 5.14)
                                (time . 1442181600)
                                (windBearing . 254)
                                (cloudCover . 0.11)
                                (pressure . 1009.4)
                                (ozone . 280.5)
                                (icon . "clear-day")
                                (summary . "Clear"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 16.09)
                                (precipProbability . 0)
                                (temperature . 29.55)
                                (apparentTemperature . 31.52)
                                (dewPoint . 20.18)
                                (humidity . 0.57)
                                (windSpeed . 5.08)
                                (time . 1442185200)
                                (windBearing . 256)
                                (cloudCover . 0.08)
                                (pressure . 1008.76)
                                (ozone . 281.33)
                                (icon . "clear-day")
                                (summary . "Clear"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 16.09)
                                (precipProbability . 0)
                                (temperature . 27.92)
                                (apparentTemperature . 29.38)
                                (dewPoint . 19.56)
                                (humidity . 0.61)
                                (windSpeed . 4.85)
                                (time . 1442188800)
                                (windBearing . 257)
                                (cloudCover . 0.04)
                                (pressure . 1008.38)
                                (ozone . 282.09)
                                (icon . "clear-day")
                                (summary . "Clear"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 16.09)
                                (precipProbability . 0)
                                (temperature . 26.28)
                                (apparentTemperature . 26.28)
                                (dewPoint . 19.26)
                                (humidity . 0.65)
                                (windSpeed . 4.18)
                                (time . 1442192400)
                                (windBearing . 256)
                                (cloudCover . 0.03)
                                (pressure . 1008.4)
                                (ozone . 282.78)
                                (icon . "clear-day")
                                (summary . "Clear"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 16.09)
                                (precipProbability . 0)
                                (temperature . 24.74)
                                (apparentTemperature . 24.74)
                                (dewPoint . 19.21)
                                (humidity . 0.71)
                                (windSpeed . 3.21)
                                (time . 1442196000)
                                (windBearing . 255)
                                (cloudCover . 0.02)
                                (pressure . 1008.68)
                                (ozone . 283.39)
                                (icon . "clear-night")
                                (summary . "Clear"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 16.09)
                                (precipProbability . 0)
                                (temperature . 23.48)
                                (apparentTemperature . 23.48)
                                (dewPoint . 19.17)
                                (humidity . 0.77)
                                (windSpeed . 2.39)
                                (time . 1442199600)
                                (windBearing . 250)
                                (cloudCover . 0.03)
                                (pressure . 1009.01)
                                (ozone . 283.81)
                                (icon . "clear-night")
                                (summary . "Clear"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 16.01)
                                (precipProbability . 0)
                                (temperature . 22.46)
                                (apparentTemperature . 22.46)
                                (dewPoint . 19.02)
                                (humidity . 0.81)
                                (windSpeed . 1.96)
                                (time . 1442203200)
                                (windBearing . 241)
                                (cloudCover . 0.09)
                                (pressure . 1009.36)
                                (ozone . 283.89)
                                (icon . "clear-night")
                                (summary . "Clear"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 15.92)
                                (precipProbability . 0)
                                (temperature . 21.43)
                                (apparentTemperature . 21.43)
                                (dewPoint . 18.69)
                                (humidity . 0.84)
                                (windSpeed . 1.8)
                                (time . 1442206800)
                                (windBearing . 228)
                                (cloudCover . 0.17)
                                (pressure . 1009.73)
                                (ozone . 283.77)
                                (icon . "clear-night")
                                (summary . "Clear"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 15.8)
                                (precipProbability . 0)
                                (temperature . 20.42)
                                (apparentTemperature . 20.42)
                                (dewPoint . 18.21)
                                (humidity . 0.87)
                                (windSpeed . 1.73)
                                (time . 1442210400)
                                (windBearing . 216)
                                (cloudCover . 0.26)
                                (pressure . 1009.96)
                                (ozone . 283.71)
                                (icon . "partly-cloudy-night")
                                (summary . "Partly Cloudy"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 15.69)
                                (precipProbability . 0)
                                (temperature . 20.26)
                                (apparentTemperature . 20.26)
                                (dewPoint . 18.41)
                                (humidity . 0.89)
                                (windSpeed . 1.67)
                                (time . 1442214000)
                                (windBearing . 207)
                                (cloudCover . 0.37)
                                (pressure . 1009.98)
                                (ozone . 283.85)
                                (icon . "partly-cloudy-night")
                                (summary . "Partly Cloudy"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 15.56)
                                (precipProbability . 0)
                                (temperature . 20.17)
                                (apparentTemperature . 20.17)
                                (dewPoint . 18.56)
                                (humidity . 0.9)
                                (windSpeed . 1.62)
                                (time . 1442217600)
                                (windBearing . 201)
                                (cloudCover . 0.49)
                                (pressure . 1009.9)
                                (ozone . 284.04)
                                (icon . "partly-cloudy-night")
                                (summary . "Partly Cloudy"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 15.48)
                                (precipProbability . 0)
                                (temperature . 19.81)
                                (apparentTemperature . 19.81)
                                (dewPoint . 18.37)
                                (humidity . 0.91)
                                (windSpeed . 1.55)
                                (time . 1442221200)
                                (windBearing . 197)
                                (cloudCover . 0.59)
                                (pressure . 1009.8)
                                (ozone . 284.11)
                                (icon . "partly-cloudy-night")
                                (summary . "Partly Cloudy"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 15.45)
                                (precipProbability . 0)
                                (temperature . 19.39)
                                (apparentTemperature . 19.39)
                                (dewPoint . 18.08)
                                (humidity . 0.92)
                                (windSpeed . 1.43)
                                (time . 1442224800)
                                (windBearing . 197)
                                (cloudCover . 0.69)
                                (pressure . 1009.69)
                                (ozone . 283.94)
                                (icon . "partly-cloudy-night")
                                (summary . "Mostly Cloudy"))
                        #hasheq((precipIntensity . 0.0229)
                                (visibility . 15.45)
                                (precipProbability . 0.01)
                                (temperature . 19.24)
                                (apparentTemperature . 19.24)
                                (dewPoint . 17.97)
                                (humidity . 0.92)
                                (windSpeed . 1.27)
                                (time . 1442228400)
                                (windBearing . 201)
                                (cloudCover . 0.77)
                                (pressure . 1009.57)
                                (ozone . 283.63)
                                (precipType . "rain")
                                (icon . "partly-cloudy-night")
                                (summary . "Mostly Cloudy"))
                        #hasheq((precipIntensity . 0.0305)
                                (visibility . 15.45)
                                (precipProbability . 0.02)
                                (temperature . 19.51)
                                (apparentTemperature . 19.51)
                                (dewPoint . 18.2)
                                (humidity . 0.92)
                                (windSpeed . 1.13)
                                (time . 1442232000)
                                (windBearing . 202)
                                (cloudCover . 0.83)
                                (pressure . 1009.55)
                                (ozone . 283.38)
                                (precipType . "rain")
                                (icon . "partly-cloudy-night")
                                (summary . "Mostly Cloudy"))
                        #hasheq((precipIntensity . 0.0279)
                                (visibility . 15.45)
                                (precipProbability . 0.01)
                                (temperature . 20)
                                (apparentTemperature . 20)
                                (dewPoint . 18.61)
                                (humidity . 0.92)
                                (windSpeed . 1.04)
                                (time . 1442235600)
                                (windBearing . 192)
                                (cloudCover . 0.87)
                                (pressure . 1009.72)
                                (ozone . 283.23)
                                (precipType . "rain")
                                (icon . "partly-cloudy-night")
                                (summary . "Mostly Cloudy"))
                        #hasheq((precipIntensity . 0.0229)
                                (visibility . 15.47)
                                (precipProbability . 0.01)
                                (temperature . 20.36)
                                (apparentTemperature . 20.36)
                                (dewPoint . 18.78)
                                (humidity . 0.91)
                                (windSpeed . 1.07)
                                (time . 1442239200)
                                (windBearing . 177)
                                (cloudCover . 0.89)
                                (pressure . 1010.02)
                                (ozone . 283.13)
                                (precipType . "rain")
                                (icon . "partly-cloudy-day")
                                (summary . "Mostly Cloudy"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 15.53)
                                (precipProbability . 0)
                                (temperature . 20.78)
                                (apparentTemperature . 20.78)
                                (dewPoint . 18.72)
                                (humidity . 0.88)
                                (windSpeed . 1.27)
                                (time . 1442242800)
                                (windBearing . 174)
                                (cloudCover . 0.86)
                                (pressure . 1010.32)
                                (ozone . 283.1)
                                (icon . "partly-cloudy-day")
                                (summary . "Mostly Cloudy"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 15.69)
                                (precipProbability . 0)
                                (temperature . 21.77)
                                (apparentTemperature . 21.77)
                                (dewPoint . 18.62)
                                (humidity . 0.82)
                                (windSpeed . 1.62)
                                (time . 1442246400)
                                (windBearing . 182)
                                (cloudCover . 0.73)
                                (pressure . 1010.53)
                                (ozone . 283.2)
                                (icon . "partly-cloudy-day")
                                (summary . "Mostly Cloudy"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 15.93)
                                (precipProbability . 0)
                                (temperature . 23.27)
                                (apparentTemperature . 23.27)
                                (dewPoint . 18.62)
                                (humidity . 0.75)
                                (windSpeed . 2.13)
                                (time . 1442250000)
                                (windBearing . 192)
                                (cloudCover . 0.54)
                                (pressure . 1010.69)
                                (ozone . 283.37)
                                (icon . "partly-cloudy-day")
                                (summary . "Partly Cloudy"))
                        #hasheq((precipIntensity . 0)
                                (visibility . 16.09)
                                (precipProbability . 0)
                                (temperature . 24.83)
                                (apparentTemperature . 24.83)
                                (dewPoint . 18.92)
                                (humidity . 0.7)
                                (windSpeed . 2.66)
                                (time . 1442253600)
                                (windBearing . 202)
                                (cloudCover . 0.43)
                                (pressure . 1010.72)
                                (ozone . 283.44)
                                (icon . "partly-cloudy-day")
                                (summary . "Partly Cloudy"))
                        #hasheq((precipIntensity . 0.0203)
                                (visibility . 16.09)
                                (precipProbability . 0.01)
                                (temperature . 26.21)
                                (apparentTemperature . 26.21)
                                (dewPoint . 19.69)
                                (humidity . 0.67)
                                (windSpeed . 3.26)
                                (time . 1442257200)
                                (windBearing . 213)
                                (cloudCover . 0.41)
                                (pressure . 1010.56)
                                (ozone . 283.34)
                                (precipType . "rain")
                                (icon . "partly-cloudy-day")
                                (summary . "Partly Cloudy"))))
                      (icon . "partly-cloudy-night")
                      (summary . "Partly cloudy until tomorrow afternoon.")))
             (daily
              .
              #hasheq((data
                       .
                       (#hasheq((precipIntensity . 0)
                                (visibility . 15.96)
                                (precipProbability . 0)
                                (dewPoint . 18.33)
                                (humidity . 0.6)
                                (windSpeed . 1.27)
                                (time . 1442041200)
                                (windBearing . 253)
                                (cloudCover . 0.46)
                                (pressure . 1012.89)
                                (ozone . 281.72)
                                (sunriseTime . 1442064816)
                                (sunsetTime . 1442109832)
                                (icon . "partly-cloudy-day")
                                (moonPhase . 0.99)
                                (precipIntensityMax . 0)
                                (temperatureMin . 23.25)
                                (temperatureMinTime . 1442059200)
                                (temperatureMax . 31.8)
                                (temperatureMaxTime . 1442098800)
                                (apparentTemperatureMin . 23.25)
                                (apparentTemperatureMinTime . 1442059200)
                                (apparentTemperatureMax . 33.98)
                                (apparentTemperatureMaxTime . 1442098800)
                                (summary . "Mostly cloudy throughout the day."))
                        #hasheq((precipIntensity . 0)
                                (visibility . 14.69)
                                (precipProbability . 0)
                                (dewPoint . 19.83)
                                (humidity . 0.72)
                                (windSpeed . 2.3)
                                (time . 1442127600)
                                (windBearing . 246)
                                (cloudCover . 0.27)
                                (pressure . 1010.72)
                                (ozone . 280.97)
                                (sunriseTime . 1442151255)
                                (sunsetTime . 1442196149)
                                (icon . "partly-cloudy-day")
                                (moonPhase . 0.02)
                                (precipIntensityMax . 0)
                                (temperatureMin . 20.42)
                                (temperatureMinTime . 1442210400)
                                (temperatureMax . 31.92)
                                (temperatureMaxTime . 1442178000)
                                (apparentTemperatureMin . 20.42)
                                (apparentTemperatureMinTime . 1442210400)
                                (apparentTemperatureMax . 35.32)
                                (apparentTemperatureMaxTime . 1442178000)
                                (summary . "Partly cloudy until afternoon."))
                        #hasheq((precipIntensity . 0.0305)
                                (visibility . 15.85)
                                (precipProbability . 0.07)
                                (dewPoint . 19.3)
                                (humidity . 0.83)
                                (windSpeed . 2.46)
                                (time . 1442214000)
                                (windBearing . 220)
                                (cloudCover . 0.6)
                                (pressure . 1010.06)
                                (ozone . 283.01)
                                (precipType . "rain")
                                (sunriseTime . 1442237695)
                                (sunsetTime . 1442282465)
                                (icon . "partly-cloudy-day")
                                (moonPhase . 0.05)
                                (precipIntensityMax . 0.0686)
                                (temperatureMin . 19.24)
                                (temperatureMinTime . 1442228400)
                                (temperatureMax . 27.94)
                                (temperatureMaxTime . 1442264400)
                                (apparentTemperatureMin . 19.24)
                                (apparentTemperatureMinTime . 1442228400)
                                (apparentTemperatureMax . 30.24)
                                (apparentTemperatureMaxTime . 1442264400)
                                (precipIntensityMaxTime . 1442278800)
                                (summary . "Mostly cloudy throughout the day."))
                        #hasheq((precipIntensity . 0.1956)
                                (visibility . 16.09)
                                (precipProbability . 0.48)
                                (dewPoint . 18.8)
                                (humidity . 0.81)
                                (windSpeed . 1.8)
                                (time . 1442300400)
                                (windBearing . 235)
                                (cloudCover . 0.43)
                                (pressure . 1012.7)
                                (ozone . 284.2)
                                (precipType . "rain")
                                (sunriseTime . 1442324135)
                                (sunsetTime . 1442368781)
                                (icon . "rain")
                                (moonPhase . 0.08)
                                (precipIntensityMax . 0.5029)
                                (temperatureMin . 18.63)
                                (temperatureMinTime . 1442314800)
                                (temperatureMax . 27.91)
                                (temperatureMaxTime . 1442350800)
                                (apparentTemperatureMin . 18.63)
                                (apparentTemperatureMinTime . 1442314800)
                                (apparentTemperatureMax . 30.01)
                                (apparentTemperatureMaxTime . 1442350800)
                                (precipIntensityMaxTime . 1442350800)
                                (summary . "Light rain until evening."))
                        #hasheq((precipIntensity . 0.0229)
                                (precipProbability . 0.03)
                                (dewPoint . 18.85)
                                (humidity . 0.77)
                                (windSpeed . 1.19)
                                (time . 1442386800)
                                (windBearing . 241)
                                (cloudCover . 0.15)
                                (pressure . 1015.25)
                                (ozone . 276.17)
                                (precipType . "rain")
                                (sunriseTime . 1442410575)
                                (sunsetTime . 1442455097)
                                (icon . "partly-cloudy-day")
                                (moonPhase . 0.11)
                                (precipIntensityMax . 0.0406)
                                (temperatureMin . 18.26)
                                (temperatureMinTime . 1442401200)
                                (temperatureMax . 32.2)
                                (temperatureMaxTime . 1442437200)
                                (apparentTemperatureMin . 18.26)
                                (apparentTemperatureMinTime . 1442401200)
                                (apparentTemperatureMax . 36.04)
                                (apparentTemperatureMaxTime . 1442437200)
                                (precipIntensityMaxTime . 1442390400)
                                (summary . "Partly cloudy in the morning."))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (dewPoint . 17.25)
                                (humidity . 0.71)
                                (windSpeed . 0.8)
                                (time . 1442473200)
                                (windBearing . 241)
                                (cloudCover . 0.05)
                                (pressure . 1014.45)
                                (ozone . 268.57)
                                (sunriseTime . 1442497015)
                                (sunsetTime . 1442541413)
                                (icon . "clear-day")
                                (moonPhase . 0.14)
                                (precipIntensityMax . 0)
                                (temperatureMin . 16.36)
                                (temperatureMinTime . 1442487600)
                                (temperatureMax . 34.57)
                                (temperatureMaxTime . 1442527200)
                                (apparentTemperatureMin . 16.36)
                                (apparentTemperatureMinTime . 1442487600)
                                (apparentTemperatureMax . 37.44)
                                (apparentTemperatureMaxTime . 1442527200)
                                (summary . "Clear throughout the day."))
                        #hasheq((precipIntensity . 0.0076)
                                (precipProbability . 0.01)
                                (dewPoint . 17.48)
                                (humidity . 0.63)
                                (windSpeed . 0.84)
                                (time . 1442559600)
                                (windBearing . 265)
                                (cloudCover . 0)
                                (pressure . 1011.06)
                                (ozone . 266.39)
                                (precipType . "rain")
                                (sunriseTime . 1442583454)
                                (sunsetTime . 1442627729)
                                (icon . "clear-day")
                                (moonPhase . 0.17)
                                (precipIntensityMax . 0.0254)
                                (temperatureMin . 17.96)
                                (temperatureMinTime . 1442574000)
                                (temperatureMax . 38.12)
                                (temperatureMaxTime . 1442613600)
                                (apparentTemperatureMin . 17.96)
                                (apparentTemperatureMinTime . 1442574000)
                                (apparentTemperatureMax . 43.32)
                                (apparentTemperatureMaxTime . 1442613600)
                                (precipIntensityMaxTime . 1442620800)
                                (summary . "Clear throughout the day."))
                        #hasheq((precipIntensity . 0)
                                (precipProbability . 0)
                                (dewPoint . 19.15)
                                (humidity . 0.68)
                                (windSpeed . 1.44)
                                (time . 1442646000)
                                (windBearing . 187)
                                (cloudCover . 0)
                                (pressure . 1008.26)
                                (ozone . 268.24)
                                (sunriseTime . 1442669894)
                                (sunsetTime . 1442714045)
                                (icon . "clear-day")
                                (moonPhase . 0.2)
                                (precipIntensityMax . 0)
                                (temperatureMin . 19.2)
                                (temperatureMinTime . 1442649600)
                                (temperatureMax . 37.89)
                                (temperatureMaxTime . 1442696400)
                                (apparentTemperatureMin . 19.2)
                                (apparentTemperatureMinTime . 1442649600)
                                (apparentTemperatureMax . 45.54)
                                (apparentTemperatureMaxTime . 1442696400)
                                (summary . "Clear throughout the day."))))
                      (icon . "rain")
                      (summary
                       .
                       "Light rain on Tuesday, with temperatures bottoming out at 28°C on Tuesday.")))
             (alerts
              .
              (#hasheq((uri
                        .
                        "http://alerts.weather.gov/cap/wwacapget.php?x=CA1253BFF58460.SpecialWeatherStatement.1253C0030950CA.LOXSPSLOX.48ddcde3addaf768468f5e5b40af47b6")
                       (title . "Special Weather Statement for Los Angeles, CA")
                       (description
                        .
                        "...EARLY SEASON RAINFALL FOR SOUTHERN CALIFORNIA MONDAY THROUGH\nWEDNESDAY...\nA DEVELOPING LOW PRESSURE SYSTEM OFF THE NORTHERN CALIFORNIA COAST\nWILL COMBINE WITH REMNANT MOISTURE FROM FORMER TROPICAL CYCLONE\nLINDA TO LIKELY BRING RAIN TO SOUTHWEST CALIFORNIA BETWEEN MONDAY\nTHROUGH WEDNESDAY. AT THIS TIME...THE MAIN THREAT OF RAIN WILL BE\nFOCUSED SOUTH OF POINT CONCEPTION...WITH THE GREATEST THREAT OF RAIN\nBETWEEN MONDAY NIGHT AND TUESDAY NIGHT. THIS SYSTEM WILL LIKELY HAVE\nOROGRAPHIC RAINFALL ENHANCEMENT...WITH COASTAL SLOPES AND FOOTHILLS\nLIKELY SEEING HIGHER RAINFALL AMOUNTS. RAINFALL AMOUNTS LOOK TO\nRANGE...FROM A FEW HUNDREDTHS TO A QUARTER OF AN INCH FOR THE\nCOASTAL AND VALLEY AREAS NORTH OF POINT CONCEPTION...TO BETWEEN ONE-\nHALF AND ONE INCH FOR THE COASTAL AND VALLEY AREAS IN LOS ANGELES\nAND VENTURA COUNTIES. RAINFALL AMOUNTS IN THE MOUNTAINS AND\nFOOTHILLS WILL RANGE FROM ONE QUARTER TO THREE-QUARTERS OF ONE INCH\nNORTH OF POINT CONCEPTION...TO BETWEEN ONE INCH AND TWO INCHES FOR\nTHE MOUNTAINS AND FOOTHILLS SOUTH OF POINT CONCEPTION.\nSINCE MANY AREAS HAVE SEEN LITTLE OR NO RAINFALL IN THE PAST COUPLE\nOF MONTHS...A BUILDUP OF OIL ON THE ROADWAYS COULD LEAD TO EXTRA\nSLIPPERY DRIVING CONDITIONS. RAINFALL COULD CAUSE MINOR URBAN\nFLOODING WHICH COULD BE WORSENED BY CLOGGED STORM DRAINS AND\nCULVERTS. MINOR MUD AND DEBRIS FLOWS ARE POSSIBLE WITH THIS SYSTEM\nFOR THE RECENTLY BURNED AREAS OF SOUTHERN CALIFORNIA. SINCE THIS\nSTORM IS ORIGINATING FROM A WARM SUBTROPICAL AIR MASS...NO SNOW IS\nEXPECTED TO FALL WITH THIS SYSTEM.\nRESIDENTS OF SOUTHERN CALIFORNIA ARE ENCOURAGED TO TAKE PRECAUTIONS\nNOW IN ADVANCE OF THE DEVELOPING WET WEATHER PATTERN ON TUESDAY.\nMOTORISTS SHOULD PREPARE FOR A LONGER AND WET COMMUTE ON MONDAY\nNIGHT AND TUESDAY. PLEASE STAY TUNED TO THE LATEST NATIONAL WEATHER\nSERVICE FORECASTS AND STATEMENTS AS THIS EARLY SEASON STORM\nCONTINUES TO DEVELOP.\n")
                       (time . 1442061600)
                       (expires . 1442106000))
               #hasheq((uri
                        .
                        "http://alerts.weather.gov/cap/wwacapget.php?x=CA1253BFF58334.BeachHazardsStatement.1253C0030950CA.LOXCFWLOX.d6e4d4672a6a1c071ce407f96f07b806")
                       (title . "Beach Hazards Statement for Los Angeles, CA")
                       (description
                        .
                        "...BEACH HAZARDS STATEMENT REMAINS IN EFFECT THROUGH THIS\nAFTERNOON...\n* HAZARDS...DANGEROUS RIP CURRENTS AND ELEVATED SURF.\n* POTENTIAL IMPACTS...THERE IS AN INCREASED RISK FOR OCEAN\nDROWNING. RIP CURRENTS CAN PULL SURFERS AND SWIMMERS OUT TO\nSEA. SNEAKER WAVES CAN SUDDENLY WASH PEOPLE OFF BEACHES AND\nROCK JETTIES.\n* WAVES AND TIMING...SURF WILL BEGIN TO SUBSIDE TODAY TO BETWEEN 3\nAND 5 FEET ACROSS SOUTH AND SOUTHEAST FACING BEACHES.\n* LOCATIONS...THE HIGHEST SURF WILL BE ON SOUTH TO SOUTHEAST\nFACING BEACHES...SUCH AS THE BEACHES FROM RINCON TO VENTURA\nPOINT...PORT HUENEME...ZUMA TO MALIBU BEACH...AND FROM\nCABRILLO TO LONG BEACH.\n")
                       (time . 1442061420)
                       (expires . 1442106000))))
             (offset . -7)
             (timezone . "America/Los_Angeles")
             (flags
              .
              #hasheq((units . "si")
                      (isd-stations
                       .
                       ("690140-93101"
                        "690160-93114"
                        "722908-99999"
                        "999999-93101"
                        "999999-93114"))
                      (madis-stations
                       .
                       ("AT067"
                        "C5283"
                        "D0553"
                        "D0558"
                        "D3439"
                        "D7047"
                        "D8020"
                        "E0066"
                        "E0881"
                        "E2249"
                        "E3225"
                        "E4246"
                        "E7328"
                        "IVRC1"
                        "KSNA"
                        "SDSTA"))
                      (lamp-stations
                       .
                       ("KCNO"
                        "KFUL"
                        "KHHR"
                        "KLGB"
                        "KNFG"
                        "KOKB"
                        "KONT"
                        "KRAL"
                        "KRIV"
                        "KSNA"
                        "KTOA"))
                      (darksky-stations . ("KSOX"))
                      (sources
                       .
                       ("nwspa"
                        "isd"
                        "nearest-precip"
                        "fnmoc"
                        "sref"
                        "rtma"
                        "rap"
                        "nam"
                        "cmc"
                        "gfs"
                        "madis"
                        "lamp"
                        "darksky"))))))